#!/bin/bash
export repo_host="centos1"
export deploy_hosts="centos1 centos2 centos3"
export project_root="/root/src/nynn/nynn_mm"
export user="root"
export data_dir="/root/subgraphset"
export nynn_ctl="${project_root}/nynn_ctl"

#deploy host->repo host
function handin(){
	host=$1;shift
	ssh ${user}@${host} ${nynn_ctl} handin $@
}

#repo host->deploy host
function handout(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} handout $@
	done
}

#repo_host->github
function sync_github(){
	ssh ${user}@${repo_host} ${nynn_ctl} sync_github $@
}

#build project_root
function build(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} build $@
	done
}

#start bins
function start_bin(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} start_bin $@ &
	done
}

#stop bins()
function stop_bin()
{
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} stop_bin $@
	done
}

function clean_data(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} clean_data $@
	done
}

function stop_iptables()
{
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} stop_iptables $@
	done
}
cmd=$1;shift

case ${cmd} in
  "handin")
  handin $@
  ;;
  "handout")
  handout $@
  ;;
  "sync_github")
  sync_github $@
  ;;
  "build")
  build $@
  ;;
  "start_bin")
  start_bin $@
  ;;
  "stop_bin")
  stop_bin $@
  ;;
  "stop_iptables")
  stop_iptables $@
  ;;
  "clean_data")
  clean_data $@
  ;;
  *)
  echo "unknown '$cmd $@'"
esac  
