#!/bin/bash
#set -x
export repo_host="centos1"
export deploy_hosts="centos1 centos2 centos3"
export project_root="/root/src/nynn/nynn_mm"
export user="root"
export data_dir="/root/subgraphset"

#deploy host->repo host
function handin(){
	pushd ${project_root}
	git add .
	git commit -a -m "$*" 
	git push repo master
	popd
}

#repo host->deploy host
function handout(){
	pushd ${project_root}
	git pull repo master
	popd
}

#repo_host->github
function sync_github(){
	pushd ${project_root}
	git push github master
	popd
}

#build project_root
function build(){
	for makefile in `find ${project_root} -type f -name "Makefile"`;do
		makefile_dir=`dirname ${makefile}`
		pushd ${makefile_dir}
		make $@
		popd
	done
}

#start bins
function start_bin(){
	pushd "${project_root}/bin"
	bin="`pwd 2>/dev/null`/$1";shift
	echo ${bin} $@
	${bin} $@ 
	popd
}

#stop bins()
function stop_bin()
{
	bin=$1
	kill -9 `ps h -C $bin -o pid`
}

function clean_data(){
	rm -fr "${data_dir}"
	mkdir -p "${data_dir}"
}

function stop_iptables()
{
	service iptables stop
}

function clean_core(){
	find ${project_root} -name "core*" -type f -exec rm -f '{}' \;
}
cmd=$1;shift

case ${cmd} in
  "handin")
  handin $@
  ;;
  "handout")
  handout $@
  ;;
  "sync_github")
  sync_github $@
  ;;
  "build")
  build $@
  ;;
  "start_bin")
  start_bin $@
  ;;
  "stop_bin")
  stop_bin $@
  ;;
  "stop_iptables")
  stop_iptables $@
  ;;
  "clean_data")
  clean_data $@
  ;;
  "clean_core")
  clean_core $@
  ;;
  *)
  echo "unknown '$cmd $@'"
esac  
