#!/bin/bash
export repo_host=`hostname`
export deploy_hosts="centos1 centos2 centos3"
export project_root="$HOME/nynn_mm"
export user="$USER"
export data_dir="$HOME/graph"
export nynn_ctl="${project_root}/nynn_ctl"
