#!/bin/bash
#set -x
export repo_host="centos1"
export deploy_hosts="centos1 centos2 centos3"
export project_root="/root/src/nynn/nynn_mm"
export user="root"
export data_dir="/root/data"

#deploy host->repo host
function handin(){
	pushd ${project_root}
	git add .
	git commit -a -m "$*" 
	git push repo master
	popd
}

#repo host->deploy host
function handout(){
	pushd ${project_root}
	git pull repo master
	popd
}

#repo_host->github
function sync_github(){
	pushd ${project_root}
	git push github master
	popd
}

#build project_root
function build(){
	for makefile in `find ${project_root}/src -type f -name "Makefile"`;do
		makefile_dir=`dirname ${makefile}`
		pushd ${makefile_dir}
		make $@
		popd
	done
}

#start bins
function nynn_run(){
	pushd "${project_root}/bin"
	bin="`pwd 2>/dev/null`/$1";shift

	pid=`ps h -C $1 -o pid`  && 
	echo $pid |grep "^[0-9]*$" 1>/dev/null 2>&1 
	if [ $? -eq 0 ]
	then
		echo "$1 is already running..."
		return 1
	fi

	if [ -f $bin ]
	then
		. `dirname $bin`/nynn_mm_env
		echo ${bin} $@
		${bin}  $@
	else
		echo "$bin not exists!"
	fi
	popd
}

#stop bins()
function nynn_stop()
{
	bin=$1
	pid=`ps h -C $bin -o pid`  && 
	echo $pid |grep "^[0-9]*$" 1>/dev/null 2>&1 
	if [ $? -eq 0 ]
	then
		echo "kill -s SIGQUIT $pid"
		kill -s SIGQUIT $pid
		return 0
	else
		echo "$bin is not running!"
	fi
}

function clean_data(){
	rm -fr "${data_dir}"
	mkdir -p "${data_dir}"
}

function stop_iptables()
{
	service iptables stop
}

function clean_core(){
	find ${project_root} -name "core*" -type f -exec rm -f '{}' \;
}
cmd=$1;shift

case ${cmd} in
  "handin")
  handin $@
  ;;
  "handout")
  handout $@
  ;;
  "sync_github")
  sync_github $@
  ;;
  "build")
  build $@
  ;;
  "nynn_run")
  nynn_run $@
  ;;
  "nynn_stop")
  nynn_stop $@
  ;;
  "stop_iptables")
  stop_iptables $@
  ;;
  "clean_data")
  clean_data $@
  ;;
  "clean_core")
  clean_core $@
  ;;
  *)
  echo "unknown '$cmd $@'"
esac  
