#!/bin/bash
export repo_host="blade4"
export deploy_hosts="blade4 blade5 blade7 blade8"
export project_root="/root/nynn_mm"
export user="root"
export data_dir="/root/graph"
export nynn_ctl="${project_root}/nynn_ctl"

#deploy host->repo host
function handin(){
	host=$1;shift
	ssh ${user}@${host} ${nynn_ctl} handin $* 
}

#repo host->deploy host
function handout(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} handout $@
	done
}

#repo_host->github
function sync_github(){
	ssh ${user}@${repo_host} ${nynn_ctl} sync_github $@
}

#build project_root
function build(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} build $@ &
	done
}

#start bins
function nynn_run(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} nynn_run $@ &
	done
}

#stop bins()
function nynn_stop()
{
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} nynn_stop $@
	done
}

function clean_data(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} clean_data $@
	done
}

function stop_iptables()
{
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} stop_iptables $@
	done
}
function clean_core(){
	for host in ${deploy_hosts};do
		ssh ${user}@${host} ${nynn_ctl} clean_core $@
	done
}
cmd=$1;shift

case ${cmd} in
  "handin")
  handin $@
  ;;
  "handout")
  handout $@
  ;;
  "sync_github")
  sync_github $@
  ;;
  "build")
  build $@
  ;;
  "nynn_run")
  nynn_run $@
  ;;
  "nynn_stop")
  nynn_stop $@
  ;;
  "stop_iptables")
  stop_iptables $@
  ;;
  "clean_data")
  clean_data $@
  ;;
  "clean_core")
  clean_core $@
  ;;
  *)
  echo "unknown '$cmd $@'"
esac  
