/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Producer_CONSTANTS_H
#define Producer_CONSTANTS_H

#include "Producer_types.h"

namespace nynn { namespace mm {

class ProducerConstants {
 public:
  ProducerConstants();

};

extern const ProducerConstants g_Producer_constants;

}} // namespace

#endif
