/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Agent_CONSTANTS_H
#define Agent_CONSTANTS_H

#include "Agent_types.h"

namespace nynn { namespace mm {

class AgentConstants {
 public:
  AgentConstants();

};

extern const AgentConstants g_Agent_constants;

}} // namespace

#endif
