/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Agent_constants.h"

namespace nynn { namespace mm {

const AgentConstants g_Agent_constants;

AgentConstants::AgentConstants() {
}

}} // namespace

