// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Provider.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::nynn::mm;

class ProviderHandler : virtual public ProviderIf {
 public:
  ProviderHandler() {
    // Your initialization goes here
  }

  bool createSubgraph(const int32_t subgraphKey) {
    // Your implementation goes here
    printf("createSubgraph\n");
  }

  bool destroySubgraph(const int32_t subgraphKey) {
    // Your implementation goes here
    printf("destroySubgraph\n");
  }

  bool attachSubgraph(const int32_t subgraphKey) {
    // Your implementation goes here
    printf("attachSubgraph\n");
  }

  bool detachSubgraph(const int32_t subgraphKey) {
    // Your implementation goes here
    printf("detachSubgraph\n");
  }

  void getSubgraphKeys(std::vector<int32_t> & _return) {
    // Your implementation goes here
    printf("getSubgraphKeys\n");
  }

  int32_t getWidthOfVertexInterval() {
    // Your implementation goes here
    printf("getWidthOfVertexInterval\n");
  }

  bool lock(const int32_t vtxno, const int32_t flag) {
    // Your implementation goes here
    printf("lock\n");
  }

  bool unlock(const int32_t vtxno) {
    // Your implementation goes here
    printf("unlock\n");
  }

  int32_t getSize(const int32_t vtxno) {
    // Your implementation goes here
    printf("getSize\n");
  }

  int32_t getHeadBlkno(const int32_t vtxno) {
    // Your implementation goes here
    printf("getHeadBlkno\n");
  }

  int32_t getTailBlkno(const int32_t vtxno) {
    // Your implementation goes here
    printf("getTailBlkno\n");
  }

  void readAllBlknos(std::vector<int32_t> & _return, const int32_t vtxno) {
    // Your implementation goes here
    printf("readAllBlknos\n");
  }

  void read(std::vector<int8_t> & _return, const int32_t vtxno, const int32_t blkno) {
    // Your implementation goes here
    printf("read\n");
  }

  void readn(std::vector<int8_t> & _return, const int32_t vtxno, const int32_t blkno, const int32_t n) {
    // Your implementation goes here
    printf("readn\n");
  }

  int32_t insertPrev(const int32_t vtxno, const int32_t nextBlkno, const std::vector<int8_t> & xblk) {
    // Your implementation goes here
    printf("insertPrev\n");
  }

  int32_t insertNext(const int32_t vtxno, const int32_t prevBlkno, const std::vector<int8_t> & xblk) {
    // Your implementation goes here
    printf("insertNext\n");
  }

  bool remove(const int32_t vtxno, const int32_t blkno) {
    // Your implementation goes here
    printf("remove\n");
  }

  int32_t unshift(const int32_t vtxno, const std::vector<int8_t> & newXHeadBlk) {
    // Your implementation goes here
    printf("unshift\n");
  }

  bool shift(const int32_t vtxno) {
    // Your implementation goes here
    printf("shift\n");
  }

  int32_t push(const int32_t vtxno, const std::vector<int8_t> & newXTailBlk) {
    // Your implementation goes here
    printf("push\n");
  }

  bool pop(const int32_t vtxno) {
    // Your implementation goes here
    printf("pop\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ProviderHandler> handler(new ProviderHandler());
  shared_ptr<TProcessor> processor(new ProviderProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

