/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Provider_CONSTANTS_H
#define Provider_CONSTANTS_H

#include "Provider_types.h"

namespace nynn { namespace mm {

class ProviderConstants {
 public:
  ProviderConstants();

};

extern const ProviderConstants g_Provider_constants;

}} // namespace

#endif
