/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Producer_constants.h"

namespace nynn { namespace mm {

const ProducerConstants g_Producer_constants;

ProducerConstants::ProducerConstants() {
}

}} // namespace

