/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Provider_constants.h"

namespace nynn { namespace mm {

const ProviderConstants g_Provider_constants;

ProviderConstants::ProviderConstants() {
}

}} // namespace

